# Generated by Django 3.1.7 on 2021-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('longitud', models.CharField(max_length=150)),
                ('latitud', models.CharField(max_length=150)),
                ('estado_geo', models.IntegerField(max_length=2)),
            ],
        ),
    ]
